Forum/Controllers/ForumController.cs
using contr8.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace contr8.Controllers;

public class ForumController : Controller
{
    private ForumDb _db { get; set; }
    private UserManager<User> _userManager { get; set; }
    private IHttpContextAccessor _httpContextAccessor;


    public ForumController(ForumDb db, UserManager<User> userManager, IHttpContextAccessor httpContextAccessor)
    {
        _httpContextAccessor = httpContextAccessor;
        _userManager = userManager;
        _db = db;
    }


    [Authorize]
    [HttpPost]
    public async Task<IActionResult> SendAnswer(string? content, int? forumId)
    {
        User? user =  await _db.Users.Include(a => a.Answers).FirstOrDefaultAsync(u => u.Id == int.Parse(_userManager.GetUserId(User)));
        ForumTitle? forum = await _db.ForumTitles.Include(a => a.Answers).FirstOrDefaultAsync(f => f.Id == forumId);
        if (!string.IsNullOrEmpty(content) && forumId.HasValue && forum != null)
        {
            Answer answer = new Answer()
            {
                CreatedTime = DateTime.UtcNow,
                Content = content,
                UserId = user.Id,
                User = user,
                ForumTitleId = forumId
            };
            _db.Answers.Add(answer);
            user.Answers.Add(answer);
            forum.Answers.Add(answer);
            _db.Users.Update(user);
            _db.ForumTitles.Update(forum);
            _db.SaveChanges();
            return Json(new { 
                isSuccess = true,
                AnwserVar = new {
                    UserAvatar = user.Avatar,
                    UserName = user.UserName,
                    CreatedTime = answer.CreatedTime.Value.ToString("dd.mm.yyyy hh:mm:ss"),
                    Content = answer.Content
                } 
            });
        }
        return Json(new {isSuccess = false});
    }
    
    public IActionResult Index()
    {
        var titles = _db.ForumTitles.Include(u => u.User).ToList();
        return View(titles);
    }

    public async Task<IActionResult> AnswersResult(int? forumId)
    {
        ForumTitle? title = await _db.ForumTitles.Include(u => u.User)
            .Include(a => a.Answers)
            .FirstOrDefaultAsync(f => f.Id == forumId);   
        var answers = _db.Answers.Include(u => u.User).Where(a => title.Answers.Select(a => a.Id).Contains(a.Id)).ToList();
        return PartialView("_AnswersResult", answers);
    }
    
    [HttpGet]
    public async Task<IActionResult> Details(int? id, int page = 1)
    {
        var referrer = _httpContextAccessor.HttpContext.Request.Headers["Referer"].ToString();
        ForumTitle? title = await _db.ForumTitles.Include(u => u.User)
            .Include(a => a.Answers)
            .FirstOrDefaultAsync(f => f.Id == id);
        var answers = _db.Answers.Include(u => u.User).Where(a => title.Answers.Select(a => a.Id).Contains(a.Id)).ToList();
        User? user = await _userManager.GetUserAsync(User);
        ViewBag.CurrentUser = user;
        int pageSize = 4;
        int count = answers.Count();
        var items = answers.Skip((page - 1) * pageSize).Take(pageSize);
        PageViewModel pvm = new PageViewModel(count, page, pageSize);
        AnswerIndexViewModel tivm = new AnswerIndexViewModel()
        {
            PageViewModel = pvm,
            Answers = items,
            ForumTitle = title
        };
        ViewBag.Answers = answers;
        if (title != null)
            return View(tivm);
        return Redirect(referrer);
    }
    
    [Authorize]
    [HttpGet]
    public async Task<IActionResult> CreateTitle()
    {
        return View();
    }

    [Authorize]
    [HttpPost]
    public async Task<IActionResult> CreateTitle(ForumTitle? model)
    {
        User? user = await _userManager.GetUserAsync(User);
        if (ModelState.IsValid)
        {
            model.UserId = user.Id;
            model.User = user;
            model.CreatedTime = DateTime.UtcNow;
            model.AnswersCount = 0;
            _db.ForumTitles.Add(model);
            user.ForumTitles.Add(model);
            _db.Users.Update(user);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        return View(model);
    }
    
    
}

Forum/Views/Forum/CreateTitle.cshtml
@model ForumTitle

@{
    ViewBag.Title = "Create Title";
    Layout = "_Layout";
}

<div class="container">
    <div class="row row-cols-1 mt-5">
        <div class="col col-6 mx-auto border border-1 py-4 px-5">
            <h5> Создание новой темы</h5>
            <form asp-action="CreateTitle" asp-controller="Forum" asp-anti-forgery="true">
                <div class="input-group mt-5">
                    <div class="validation text-danger" asp-validation-summary="ModelOnly"></div>
                    <label for="title"><span class="text-danger" asp-validation-for="Title"></span></label>
                    <div class="input-group">
                        <input asp-for="Title" type="text" class="form-control" placeholder="ForumTitle Title" id="title">
                    </div>
                    <label for="cont"><span class="text-danger" asp-validation-for="Content"></span></label>
                    <div class="input-group mt-3">
                        <textarea class="form-control h-100" asp-for="Content" placeholder="Content" type="text" id="cont" rows="4"></textarea>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary rounded-2 w-100 mt-3">Создать новую тему</button>
            </form>
        </div>
    </div>
</div>

Forum/Views/Forum/Details.cshtml
@model AnswerIndexViewModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
<header>
  <h2>
    <strong><a class="mx-3" asp-action="Profile" asp-controller="Account" asp-route-userId="@Model.ForumTitle.UserId">@Model.ForumTitle.User.UserName</a></strong><i class="fa fa-angle-right"></i><span class="mx-3"> @Model.ForumTitle.Title</span> <i class="fa fa-angle-right"></i><span class=""> @Model.ForumTitle.CreatedTime</span>
  </h2>
</header>
<div class="response-group">
  <div class="response">
    <div class="response__number">
      @Model.ForumTitle.Id
    </div>
    <h1 class="response__title">  
      @Model.ForumTitle.Content
    </h1>
    @if (User.Identity.IsAuthenticated)
    {
      <button class="btn btn-primary" id="down-scroll">Ответить</button>
    }
    @{
      int i = 1;
    }
    <div class="post-group" id="answers">
      <div class="num"></div>
      @foreach (var answer in @Model.Answers)
      {
        <div data-num="@i" class="post">
          <div class="post__avatar">
            <img src="@answer.User.Avatar" class="msgimg"/>
          </div>
          <h3 class="post__author">
            @answer.User.UserName
          </h3>
          <h4 class="post__timestamp">
            @answer.CreatedTime
          </h4>
          <p class="post__body">
            @answer.Content
          </p>
          <div class="post__actions">
            <div class="button button--approve">
              <i class="fa fa-thumbs-o-up"></i><i class="fa fa-thumbs-up solid"></i>
            </div>
            <div class="button button--deny">
              <i class="fa fa-thumbs-o-down"></i><i class="fa fa-thumbs-down solid"></i>
            </div>
          </div>
        </div>
        i++;
      }
    </div>
    <div class="paginator" id="page">
    </div>
    @if (User.Identity.IsAuthenticated)
    {
      <div class="post__actions w-50" id="comment-to-scroll">
        <div class="button button--fill comment-trigger">
          <span>Comment...</span>
        </div>
        <div class="button button--flag">
          <i class="fa fa-comment-o"></i><i class="fa fa-comment solid"></i>2
        </div>
        <div class="post__comments">
          <div class="comment-form">
            <div class="comment-form__avatar" id="error">
              <img src="@ViewBag.CurrentUser.Avatar" class="msgimg"/>
            </div>
            <textarea id="comment-content"></textarea>
            <div class="comment-form__actions">
              <div class="button button--light cancel">
                Cancel
              </div>
              <div class="button button--confirm" id="comment-button">
                Comment
              </div>
            </div>
          </div>
        </div>
        
      </div>
    }
    <div class="col-4 mx-auto text-center">
                @if (Model.PageViewModel.HasPreviousPage)
                { <a class="btn btn-primary me-4" asp-action="Details" asp-route-id="@Model.ForumTitle.Id" asp-route-page="@(Model.PageViewModel.PageNumber - 1)"> Предыдущий </a> }
                @if (Model.PageViewModel.HasNextPage)
                { <a class="btn btn-primary ms-4" asp-action="Details" asp-route-id="@Model.ForumTitle.Id" asp-route-page="@(Model.PageViewModel.PageNumber + 1)"> Следующий </a> }</div>
  </div>
</div>

@section Scripts
{
  <script>
    function sendAnswer(data){
      $('#answers').append(`
        <div class="post">
          <div class="post__avatar">
            <img src="${data.userAvatar}" class="msgimg"/>
          </div>
          <h3 class="post__author">
            ${data.userName}
          </h3>
          <h4 class="post__timestamp">
            ${data.createdTime}
          </h4>
          <p class="post__body">
            ${data.content}
          </p>
        </div>
      `);
    }

    $().ready(function (){
     
     
      $('#comment-button').click(function (e){
        console.log('click');
        e.preventDefault();
        let comment = $('#comment-content').val();
        let forumId = @Model.ForumTitle.Id;
        $.ajax({
          url: '@Url.Action("SendAnswer", "Forum")',
          type: 'POST',
          data: {  'content' : comment, 'forumId': forumId },
          success: function(data){
            console.log(data);
            if (data.isSuccess == true){
              console.log('check answer messa');
              console.log(data.anwserVar);
              sendAnswer(data.anwserVar);
            }else{
              $('#error').html('<span class="text-danger">Невозможно отправить ответ!</span>');
            }
          }
        }); 
      });
    });
  </script>
}

Forum/Views/Forum/Index.cshtml
@model List<ForumTitle>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
<div class="text-center">
    <h1 class="mx-auto"> Темы </h1>
</div>
<div class="table_section mt-4">
    @if (@Model.Count == 0)
    {
        <p>Пока что, животных еще нет!</p>
    }
    else
    {
        <table class="table table-warning table-striped">
            <thead>
                <tr>
                    <th>Основная тема</th>
                    <th>Дата добавления</th>
                    <th>Автор</th>
                    <th>Ответы</th>
                </tr>            
            </thead>
            <tbody>
            @foreach (var title in @Model)
            {
                <tr>
                    <td><a asp-action="Details" asp-controller="Forum" asp-route-id=@title.Id class="nav-link text-dark">@title.Title</a></td>
                    <td><a asp-action="Details" asp-controller="Forum" asp-route-id=@title.Id class="nav-link text-dark">@title.CreatedTime</a></td>
                    <td><a asp-action="Details" asp-controller="Forum" asp-route-id=@title.Id class="nav-link text-dark">@title.User.UserName</a></td>
                    <td><a asp-action="Details" asp-controller="Forum" asp-route-id=@title.Id class="nav-link text-dark">@title.AnswersCount</a></td>
                </tr>
            }            
            </tbody>
        </table>
    }
</div>

Forum/Views/Forum/_AnswersResult.cshtml
@model List<Answer>

@{
    int i = 1;
}
<div class="post-group" id="answers">
    @foreach (var answer in @Model)
    {
        <div data-num="@i" class="post num" id="answer-@i">
            <div class="post__avatar">
                <img src="@answer.User.Avatar" class="msgimg"/>
            </div>
            <h3 class="post__author">
                @answer.User.UserName
            </h3>
            <h4 class="post__timestamp">
                @answer.CreatedTime
            </h4>
            <p class="post__body">
                @answer.Content
            </p>
            <div class="post__actions">
                <div class="button button--approve">
                    <i class="fa fa-thumbs-o-up"></i><i class="fa fa-thumbs-up solid"></i>
                </div>
                <div class="button button--deny">
                    <i class="fa fa-thumbs-o-down"></i><i class="fa fa-thumbs-down solid"></i>
                </div>
            </div>
        </div>
        i++;
    }
</div>